workflows:
  android-workflow:
    name: Android Build
    instance_type: linux_x2
    environment:
      java: default
      ndk: r21e
      android_sdk_version: android-36
      xcode: latest
      flutter: stable
      groups:
        - google_play # Firebase 等凭证组
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # 改成你的邮箱
      slack:
        channel: '#builds'  # 如果有 Slack

  web-workflow:
    name: Web Build
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**/*
    publishing:
      email:
        recipients:
          - your-email@example.com

  windows-workflow:
    name: Windows Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Windows
        script: flutter build windows --release
    artifacts:
      - build/windows/runner/Release/*.exe
    publishing:
      email:
        recipients:
          - your-email@example.com
