workflows:
  android-workflow:
    name: Android Build
    instance_type: linux_x2
    environment:
      java: default
      ndk: r21e
      android_sdk_version: android-36
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
