// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:web:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    authDomain: 'uyghur-translation-app.firebaseapp.com',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
    measurementId: 'G-ABCD1234EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:android:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
    androidClientId: 'abc123.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:ios:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
    iosBundleId: 'com.example.uyghurTranslatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:macos:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
    iosBundleId: 'com.example.uyghurTranslatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:windows:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQR',
    appId: '1:123456789012:linux:abc123def456ghi789jkl',
    messagingSenderId: '123456789012',
    projectId: 'uyghur-translation-app',
    databaseURL: 'https://uyghur-translation-app.firebaseio.com',
    storageBucket: 'uyghur-translation-app.appspot.com',
  );
}
